version: "3.8"
services:
  discord-sg:
    build: .
    container_name: discord-sg
    restart: always
    networks:
      - app-network

  discord-db:
    image: postgres
    container_name: discord_pgdb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - discord-local_pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  discord-pgadmin:
    image: dpage/pgadmin4
    container_name: discord_pgadmin4
    restart: always
    ports:
      - "8085:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - discord-pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

volumes:
  discord-local_pgdata:
  discord-pgadmin-data:

networks:
  app-network:
    driver: bridge